class Gares {
  static const List<String> listeGares = [
    "Paris Gare de Lyon",
    "Paris Montparnasse",
    "Paris Gare du Nord",
    "Paris Saint-Lazare",
    "Strasbourg",
    "Lille Europe",
    "Bordeaux Saint-Jean",
    "Rennes",
    "Marseille Saint-Charles",
    "Nantes",
    "Paris Est",
    "Lyon Perrache",
    "Toulouse Matabiau",
    "Lyon Part Dieu",
    "Brest",
    "Nice",
    "Montpellier Saint-Roch",
    "Mulhouse",
    "Paris Austerlitz",
    "Tours",
    "Orléans",
    "Hendaye",
    "La Rochelle",
    "Nancy",
    "Quimper",
    "Le Mans",
    "Grenoble",
    "Caen",
    "Dijon",
    "Metz Ville",
    "Perpignan",
    "Rouen Rive Droite",
    "Poitiers",
    "Aéroport Charles de Gaulle 2 TGV",
    "Angers Saint-Laud",
    "Clermont-Ferrand",
    "Cherbourg",
    "Avignon TGV",
    "Annecy",
    "Le Havre",
    "Chambéry - Challes-les-Eaux",
    "Paris Bercy",
    "Amiens",
    "Valence",
    "Tarbes",
    "Toulon",
    "Saint-Étienne Châteaucreux",
    "Marne-la-Vallée Chessy",
    "Tourcoing",
    "Montpellier Sud de France",
    "Brive-la-Gaillarde",
    "Bourges",
    "Limoges Bénédictins",
    "Besançon Viotte",
    "Nîmes",
    "Aix-en-Provence TGV",
    "Saint-Nazaire",
    "Agen",
    "Narbonne",
    "Dunkerque",
    "Chartres",
    "Périgueux",
    "Reims",
    "Colmar",
    "Nevers",
    "Vierzon",
    "Cannes",
    "Boulogne Ville",
    "Le Croisic",
    "Massy TGV",
    "Béziers",
    "Mantes-la-Jolie",
    "Valence TGV Rhône-Alpes Sud",
    "Saint-Pierre-des-Corps",
    "Bourg-Saint-Maurice",
    "Avignon Centre",
    "Les Aubrais",
    "Pau",
    "Laroche - Migennes",
    "Granville",
    "Creil",
    "Bayonne",
    "Dax",
    "Niort",
    "Angoulême",
    "Bellegarde",
    "Compiègne",
    "Bourg-en-Bresse",
    "Haguenau",
    "Arras",
    "Sélestat",
    "Lorient Bretagne Sud",
    "Saintes",
    "Roanne",
    "Douai",
    "Saint-Brieuc",
    "Calais Ville",
    "Saint-Malo",
    "Épinal",
    "Montauban Ville Bourbon"
  ];
}