class Objets {
  static const List<String> listeObjets = [
    "Porte-monnaie, portefeuille",
    "Sac à dos",
    "Valise, sac sur roulettes",
    "Téléphone portable",
    "Manteau, veste, blazer, parka, blouson, cape",
    "Sac de voyage, sac de sport, sac à bandoulière",
    "Clés, porte-clés",
    "Carte d\'identité, passeport, permis de conduire",
    "Sac d\'enseigne (plastique, papier, …)",
    "Lunettes",
    "Sac à main",
    "Téléphone portable protégé (étui, coque,…) ",
    "Carte de crédit",
    "Lunettes en étui",
    "Autres divers",
    "Bonnet, chapeau",
    "Foulard, écharpe",
    "Carte d\'abonnement",
    "Pièce d\'identité personnelle et autre",
    "Ordinateur, ordinateur portable, notebook",
    "Autres appareils et accessoires électroniques",
    "Pull over, gilet",
    "Autre pièce ou papier personnel",
    "Sacoche ventrale, banane",
    "Autre bagagerie",
    "Autres vêtements",
    "Tablette tactile protégée (étui, housse)",
    "Nécessaire, mallette de toilette, sac de maquillage",
    "Sacoche pour ordinateur, photo, vidéo",
    "Casque (vélo, moto)",
    "AirPod, casque audio, écouteurs",
    "Vélo",
    "Parapluie télescopique, parapluie de poche",
    "Ordinateur, ordinateur portable, notebook protégé (étui, housse,…) ",
    "Parapluie-canne, parapluie à bandoulière",
    "Autres articles de papeterie",
    "Attaché-case, serviette",
    "Doudou, peluche",
    "Gants",
    "Sacs de couchage, duvet",
    "Chaussures (autre que chaussures de ski et patins)",
    "Livre de poche",
    "Carte Vitale",
    "Clé de voiture",
    "Montre",
    "Article de papéterie, stylo, classeur",
    "Autre livre",
    "Chemise à rabat",
    "Livre numérique",
    "Tablette tactile",
    "Trottinette",
    "Autres articles enfants, bébé",
    "Bracelet",
    "Appareil audio portable (lecteur de CD, baladeur MP3, iPod, ... )",
    "Appareil photo, caméscope/caméras et accessoires",
    "Outils, Accesoires",
    "Autres articles de sport, de loisirs ou de camping",
    "Agenda, calendrier",
    "Bague",
    "Appareil photo, caméscope/caméras et accessoires protégé (sac, sacoche,…) ",
    "Badge magnétique",
    "Landau, poussette d\'enfants",
    "Cartable, trousse d\'écolier, dossier scolaire",
    "Disque dur externe, clé USB",
    "Chéquier",
    "Billets SNCF",
    "Diplôme, papiers personnels",
    "Raquette de tennis, de badminton",
    "Argent liquide / Espèces",
    "Canne",
    "Housse de vêtement",
    "Tente",
    "Chaîne, collier",
    "Autres instruments de musique",
    "Guitare",
    "Autres articles médicaux",
    "Livre relié",
    "Cartable à dessins, pochette à dessins",
    "Etui à lunettes vide",
    "Skateboard",
    "Médicaments",
    "Radiographie",
    "Autre argent",
    "Accessoires 2 roues",
    "Appareils audio portables (lecteur de CD, baladeur MP3, iPod, etc. )",
    "Boucles d\'oreilles",
    "Appareils respiratoire avec ou sans protection",
    "Bâton de marche",
    "Béquilles",
    "Couteau de poche, autre couteau",
    "Autres jeux/jouets ",
    "Produits cosmétiques (parfum, etc.)",
    "Autre petit véhicule",
    "Jeu électronique (console de jeux: Gameboy, PSP, DS, …)",
    "Tabac et accessoire",
    "Photos, albums de photos",
    "Livre scolaire",
    "Appareils auditifs",
    "Téléviseur, magnétoscope, lecteur DVD, radio",
    "Accessoires de musique"
  ];
}
